### ISSUE TITLE
[ENH] - Finish creating the 5km Grid for CONUS

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/DeploymentOrderTool#11]
### Which app?

Deployment Order Tool 2.0

### Describe requirements

Create the 5km Grid for all of CONUS.

### Alternatives

If this does not work, we may need to simply use the 10km grid. 

### Other Relevant Info

Chris is working on it but had some issues with getting all of the grids to align.

### Priority impact

p1 - time sensitive

### Impact

We cannot do much more User Acceptance Testing until this is complete.

**Comment by cjonesroberts** [comment]
@pjdohertygis I have the grids generated and the drive distances calculated for CONUS. I am just working on some post processing pieces but I should have the layer updated today. For the HEPP/IST field. Which of the fields circled should I pull over? should I convert it to a Colocated with IST Y/N? field and a Colocated with HEPP Y/N? field? or should then be combined like the field on the right? 
![image](https://github.com/pjdohertygis/DeploymentOrderTool/assets/72469018/b733cf61-2abb-417e-bd55-d8b6c6a3238d)

**Comment by pjdohertygis** [comment]
The one on the left - this way they can see which one it is as well. Thank you!On Mar 15, 2024, at 09:53, Chris Jones-Roberts ***@***.***> wrote:﻿
@pjdohertygis I have the grids generated and the drive distances calculated for CONUS. I am just working on some post processing pieces but I should have the layer updated today. For the HEPP/IST field. Which of the fields circled should I pull over? should I convert it to a Colocated with IST Y/N? field and a Colocated with HEPP Y/N? field? or should then be combined like the field on the right?
image.png (view on web)

**Comment by pjdohertygis** [comment]
@cjonesroberts once we are sure this is "the script" - see if you can upload it to our Git repo with any relevant documentation.
