### ISSUE TITLE
[ENH] - Prevent table from loading or being visible until a selection is made

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/DeploymentOrderTool#12]
### Which app?

Deployment Order Tool 2.0

### Describe requirements

We would like the end user to only see the table (or contents in the able) once a grid selection is made. Is there a way to only load the table once the map is clicked on? Only open the side panel once the map is clicked on? Any other ideas?

### Alternatives

We could use "select" action instead of "filter" action. This makes the table "blank" until the grid is clicked on, but then the table is highlighted and does not allow for a copy / paste from the app. 

We could also hide the slide panel when it loads and tell the user not to open until they click on the map?

### Other Relevant Info

This is what it looks like when it loads - the table does not mean anything. 
![image](https://github.com/pjdohertygis/DeploymentOrderTool/assets/4256979/29c19e79-98da-428b-ad2c-cdc21063df10)

### Priority impact

p0 - not time sensitive

### Impact

It is just a little confusing for the end user, they will see strange results in the table and might not know that the selection has not yet been made.

**Comment by pjdohertygis** [comment]
This may end up being related to https://github.com/pjdohertygis/DeploymentOrderTool/issues/13

**Comment by avezina** [comment]
It seems Selected features would resolve the workflow, but the main limitation is that the table is highlighted and does not allow to easily copy / paste from the table. If the Button widget supported Exporting the connected data to a CSV, would that resolve the issue?
![image](https://github.com/pjdohertygis/DeploymentOrderTool/assets/50338557/49a09ca7-a5ef-4a69-bd4b-66269d2d9c3a)

Then you'd be able to add a Export button near the Table.

This would need to be a new enhancement request for Experience Builder.

**Comment by pjdohertygis** [comment]
I like the idea of export csv as a button as it would be more intuitive than the current interface 
![image](https://github.com/pjdohertygis/DeploymentOrderTool/assets/4256979/a40fc7c8-ce1b-454c-9ba3-eb71e189c9ee)

However, that would just be a nice to have. 

I'll show our users the interaction if we go with Select vs Filter and see what they think. It is really handy to be able to copy and paste right from the app because they have a separate excel file they paste it into.

**Comment by pjdohertygis** [comment]
If we implement this - let's double check performance of export over various levels of connectivity 

![image](https://github.com/pjdohertygis/DeploymentOrderTool/assets/4256979/3077697c-1305-4831-ae95-55d6b257b070)

**Comment by pjdohertygis** [comment]
Ok using the approach @avezina mentioned seems to work. 

![image](https://github.com/pjdohertygis/DeploymentOrderTool/assets/4256979/b97298ea-4d13-44f0-8a15-83e1ac39082e)

The table loads blank until a selection is made 
![image](https://github.com/pjdohertygis/DeploymentOrderTool/assets/4256979/c0a35e76-5a30-48e9-9bbf-43f6722329ed)

And you can still copy/paste from the table! The csv download actually appears to be faster than using the "filter" approach.

Closing unless we receive feedback that this doesn't work for some reason.

**Comment by pjdohertygis** [comment]
Closing unless we receive feedback that this doesn't work for some reason.
