### ISSUE TITLE
[ENH] - Replace State EOC Layer from HIFLD

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/DeploymentOrderTool#19]
### Which app?

Other

### Describe requirements

Replace the State EOC Layer with whatever is the latest.
https://fema.maps.arcgis.com/home/item.html?id=5ff4e9ca6fa94d62bfd14b8d70d7ad0d
![image](https://github.com/pjdohertygis/DeploymentOrderTool/assets/4256979/1ebdd1a6-88f0-463c-87e0-1b141998a747)

### Alternatives

None

### Other Relevant Info

This is linked to the NearMe widget as well. 

### Priority impact

p1 - time sensitive

### Impact

This may eventually break the app!

**Comment by pjdohertygis** [comment]
We are still waiting to hear back from HIFLD on the correct data source right @jdokemaps ?

**Comment by jdokemaps** [comment]
> We are still waiting to hear back from HIFLD on the correct data source right @jdokemaps ?

@pjdohertygis Correct. I just emailed the HIFLD Team again to see if they had any additional information.

**Comment by pjdohertygis** [comment]
We have been given permission to use this layer @jdokemaps - please evaluate and if appropriate - make it so 
https://fema.maps.arcgis.com/home/item.html?id=40ea5292e32045499691baeffeda8c00
